// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9xuogZKiqvCjWa5_hUveD0Qt4sU_GBg',
    appId: '1:667522263901:web:b1067f458f335d46a356b4',
    messagingSenderId: '667522263901',
    projectId: 'unitrade-5b903',
    authDomain: 'unitrade-5b903.firebaseapp.com',
    storageBucket: 'unitrade-5b903.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEY8YN8O-tVjvoCgdjR8dn_n011OFrSM',
    appId: '1:667522263901:android:aaf504fdab65db91a356b4',
    messagingSenderId: '667522263901',
    projectId: 'unitrade-5b903',
    storageBucket: 'unitrade-5b903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICFuSWQ0MfM-hcFXLt-RPjvN-9nmlA9Y',
    appId: '1:667522263901:ios:13fdb737f36be6aba356b4',
    messagingSenderId: '667522263901',
    projectId: 'unitrade-5b903',
    storageBucket: 'unitrade-5b903.appspot.com',
    iosClientId: '667522263901-glpre0om3gtu4tpepsnjsj1jh2fjdmef.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniTrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDICFuSWQ0MfM-hcFXLt-RPjvN-9nmlA9Y',
    appId: '1:667522263901:ios:e55811c7c0507ebfa356b4',
    messagingSenderId: '667522263901',
    projectId: 'unitrade-5b903',
    storageBucket: 'unitrade-5b903.appspot.com',
    iosClientId: '667522263901-frnrdvh94lvmlub8e93580p9j84r8rcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniTrade.RunnerTests',
  );
}
